### PR TITLE
just decided to add a file

### PR DESCRIPTION
**Pull request by preqs**
its ok if you dont accept pull request

### CODE REVIEW

**Comment by retest672** [comment]
ok i got the example i will merge just can you send another pull request containing the program and readme after I merge?

**Comment by preqs** [comment]
yep

**Comment by retest672** [comment]
ok
here i go

**Comment by preqs** [comment]
sorry i havent got the program

**Comment by retest672** [comment]
its ok i think i can replicate it and upload the file

**Comment by retest672** [comment]
i just wanna know what programming language is required?

**Comment by preqs** [comment]
scratch

**Comment by retest672** [comment]
ok

**Comment by retest672** [comment]
it will probably take 5 days to 3 weeks to get this done depending on how much stuff I have to do

**Pull request merged**
